version: "3"
services:
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
  mysql:
    image: mysql:5.6
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
    volumes:
      - ./share/mysql/data:/var/lib/mysql
  elasticsearch:
    image: elasticsearch:5.6.15
    container_name: elasticsearch
    ports:
    - "9200:9200"
    environment:
    - cluster.name=docker-cluster
    - bootstrap.memory_lock=true
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
    - ./share/elasticsearch5.6.15/data:/usr/share/elasticsearch/data
    - ./share/elasticsearch5.6.15/plugins:/usr/share/elasticsearch/plugins